# Generated by Django 4.1.4 on 2022-12-23 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_name', models.CharField(max_length=100, verbose_name='Назва файлу')),
                ('prediction_image', models.ImageField(upload_to='media/', verbose_name='Зображення')),
                ('prediction_prob', models.CharField(max_length=20, verbose_name='Впевненість')),
            ],
        ),
    ]
