# Generated by Django 4.1.4 on 2022-12-24 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_rename_prediction_image_predictionmodel_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionmodel',
            name='classification',
            field=models.CharField(default=1, max_length=100, verbose_name='Клас'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='predictionmodel',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Зображення'),
        ),
    ]
