# Generated by Django 4.1.4 on 2022-12-25 20:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_predictionmodel_classification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictionmodel',
            name='image',
            field=models.ImageField(upload_to='', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'svg'])], verbose_name='Зображення'),
        ),
    ]
